name: Code Insight Scan

on:
  workflow_dispatch

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
  code_insight_scan:
    runs-on: self-hosted
    env:
      CODEINSIGHT_SERVER: http://localhost:8888
      AUTH_TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZ2VhcnkiLCJ1c2VySWQiOjksImlhdCI6MTY2OTEzNTc1N30.LSc-K5H7hr_j_olZZ9aK5rxhUx9evqri6CUo8WikSC-mq0uWIBG0ZJ7cKsrIdtJrnGAFIQcpURsdPO7m5VueHw
      CODEINSIGHT_PROJECT: My Application v3.1
      HOSTNAME: WFH-LT-103659
      ALIAS: github-actions-runner
      JARFILE: D:\GITREPOS\SCA\CodeInsight\GitHub\generic-plugin-binary\codeinsight-generic-3.1.7-SNAPSHOT.jar
    steps:
      - name: Windows Runner
        if: runner.os == 'Windows'
        run: |
          echo "The operating system on the runner is $env:RUNNER_OS."
          echo "The workspace is $env:GITHUB_WORKSPACE."
          echo "My Variable is $env:AUTH_TOKEN."
          echo  java -jar $env:JARFILE -server $env:CODEINSIGHT_SERVER -token "Bearer $env:AUTH_TOKEN" -proj "$env:CODEINSIGHT_PROJECT" -root "$env:GITHUB_WORKSPACE" -scandirs "$env:GITHUB_WORKSPACE"  -alias "$env:ALIAS" -host "$env:HOSTNAME"  

      
      - name: Non Windows Runner
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
